sudo: required

language: python

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install coveralls
    - sudo -HE pip install .

script:
    - coverage run --source=kubos-sdk setup.py test

after_success:
    - coveralls
