sudo: required

language: python

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip list
    - touch ./lib/osx/libanalytics.dylib
    - sudo -HE pip install .

script:
    - python setup.py test
